### ISSUE TITLE
Extension causes error when loading any JavaScript file

### ISSUE THREAD

**Issue by oblitum** [felippepuhle/coc-graphql#1]
This will be shown for any `foo.js` file I open:

```
[coc.nvim] Request initialize failed with message: GraphQL Config file is not available in the provided config directory: /really/any/directory
Please check the config directory.
```

**Comment by oblitum** [comment]
There's no GraphQL involved in the project, so there's no configuration for that, but having the plugin with trigger this error.

**Comment by felippepuhle** [comment]
Can confirm this, we should manually handle  `loadConfig` to avoid this.

**Comment by acao** [comment]
hmmm... this should not be failing in this manner. 

this is the offending line:

https://github.com/graphql/graphiql/blob/2a48066e55de2eca8cb40654de8181fe5364aeaa/packages/graphql-language-service-server/src/MessageProcessor.ts#L239

i should change this to a warning, as the LSP server should work fine when it's been activated but no graphql config is present. this error is logged silently in the vscode output channel, but here it shouldn't be doing this!

**Comment by acao** [comment]
Do you have the ability to determine activation events similarly to how we do in vscode? this ensures the language server is only started when a graphql config file is present and/or when .graphql files are present.

https://github.com/prisma-labs/vscode-graphql/blob/7d6fc83a5c70997b23bd410596d103e4de08f458/package.json#L35

**Comment by acao** [comment]
https://github.com/graphql/graphiql/pull/1669 i think this should take care of it!

are you able to respond to workspace settings requests? the users can provide some settings that are used in the LSP server now

**Comment by felippepuhle** [comment]
> Do you have the ability to determine activation events in coc.nvim similarly to how we do in vscode? this ensures the language server is only started when a graphql config file is present and/or when .graphql files are present.
> 
> https://github.com/prisma-labs/vscode-graphql/blob/7d6fc83a5c70997b23bd410596d103e4de08f458/package.json#L35

I think so @acao, I didn't update the LSP yet so we might need to work on it too.

Thanks!

**Comment by felippepuhle** [comment]
I think I'm going to deprecate this package, I'm very short on time so I probably won't add any new features/integrations, and we can still use the LSP directly via CoC configuration: https://github.com/neoclide/coc.nvim/wiki/Language-servers#graphql

**Comment by ledesmablt** [comment]
Thanks for the above suggestion, it works perfectly fine for me (didn't know about `languageserver` too). I think it would minimize confusion if you formalize the deprecation on the readme and npm =)

**Comment by felippepuhle** [comment]
Done, thanks for the suggestion @ledesmablt
