### ISSUE TITLE
Content-Length property error?

### ISSUE THREAD

**Issue by xorander00** [felippepuhle/coc-graphql#2]
Not sure if I'm screwing up something or if it's extension-specific code, but whenever I try to open a .graphql file, coc.nvim reports this error...  
  
2020-09-29T06:26:11.609 ERROR (pid:75588) [server] - uncaughtException Error: Header must provide a Content-Length property.  
  
From what little I've read thus far, it indicates that maybe it's the extension misbehaving?  Anyone else getting this error?

**Comment by felippepuhle** [comment]
This package has been deprecated, you can still have the same functionalities using the [LSP config on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 

Also, your problem may have been fixed on a new version of the language server (which this CoC extension doesn't provide). Feel free to reopen this issue if needed, or even contacting the [GraphQL LSP folks](https://github.com/graphql/graphiql) directly.

Thanks!
