### ISSUE TITLE
No diagnostics?

### ISSUE THREAD

**Issue by andrestone** [felippepuhle/coc-graphql#3]
Using latest coc-graphql / vim-graphql / coc-nvim / vim 8.2

`graphql.config.yml`
```yaml
schema: ./schema.graphql
```

When editing `schema.graphql` I get diagnostics for syntax but not for type errors (reference to inexistent types aren't diagnosed, for example).

**Comment by felippepuhle** [comment]
This package has been deprecated, you can still have the same functionalities using the [LSP config on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 

Also, your problem may have been fixed on a new version of the language server (which this CoC extension doesn't provide). Feel free to reopen this issue if needed, or even contacting the [GraphQL LSP folks](https://github.com/graphql/graphiql) directly.

Thanks!
