### ISSUE TITLE
Make the GraphQL config file at root optional

### ISSUE THREAD

**Issue by sgalizia** [felippepuhle/coc-graphql#4]
The necessity to have a gql config file at the project root causes so many issues that I am about to disable this and remove it. I Really enjoy the syntax highlighting and recognition, but I work on a large project with a repo that has many projects in it and I can not just add a gql config. The plugin clearly works without it, so just make it optional please so I am not getting bombarded with error messages every time I open a project (not even a gql file).

**Comment by Rblock919** [comment]
Agreed, it would be nice to turn that feature off and only be left with syntax highlighting and term recognition. On typescript GQL projects where you take a code-first approach it is not necessary to jump to def/ref on graphql types, but when validating generated GQL schema files it is still nice to have syntax highlight and term recognition.

**Comment by sgalizia** [comment]
realized I have made a mistake here and that I don't actually need coc-graphql. Apologies!

**Comment by vuki656** [comment]
@sgalizia How did you get around the issue? 

I also need syntax highlighting but putting a config file in every project to prevent errors seems unnecessary.

**Comment by sgalizia** [comment]
Syntax highlighting is not provided by by this plugin. The plugin `vim-graphql` by jparise achieves that if you are solely looking for syntax highlighting.

**Comment by vuki656** [comment]
> Syntax highlighting is not provided by by this plugin. The plugin `vim-graphql` by jparise achieves that if you are solely looking for syntax highlighting.

Thanks. How did you handle auto completion?

**Comment by destructobeam** [comment]
Can this issue be re-opened please? It is still a valid problem when opening JS files that don't use GraphQL, and therefore don't require a config file.
