### ISSUE TITLE
A way to set a custom graphql config path

### ISSUE THREAD

**Issue by narajaon** [felippepuhle/coc-graphql#6]
When working in a monorepo, the root of the monorepo is not where your config file will be.
Let's implement a way to customize the project root of the plugin.

**Comment by felippepuhle** [comment]
I'd recommend you to use the [LSP directly ](https://github.com/neoclide/coc.nvim/wiki/Language-servers#graphql) instead of this package, I'm not using nvim for a while and unfortunately, I don't have time to improve it (PRs are welcome).

**Comment by felippepuhle** [comment]
This package has been deprecated, you can still have the same functionalities using the [LSP config on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 

Also, your problem may have been fixed on a new version of the language server (which this CoC extension doesn't provide). Feel free to reopen this issue if needed, or even contacting the [GraphQL LSP folks](https://github.com/graphql/graphiql) directly.

Thanks!
