### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by yassinebridi** [felippepuhle/coc-graphql#7]
Currently coc-graphql doesn't format on save graphql files, even if you put this in coc-settings.json
```json
"coc.preferences.formatOnSaveFiletypes": [
  "graphql",
],
```

**Comment by felippepuhle** [comment]
This package has been deprecated, you can still have the same functionalities using the [LSP config on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 

Also, your problem may have been fixed on a new version of the language server (which this CoC extension doesn't provide). Feel free to reopen this issue if needed, or even contacting the [GraphQL LSP folks](https://github.com/graphql/graphiql) directly.

Thanks!
