### ISSUE TITLE
The graphql server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by nstylo** [felippepuhle/coc-graphql#8]
![image](https://user-images.githubusercontent.com/45883614/106464286-bd612900-6498-11eb-93dd-01643f1f8ae7.png)

After installing coc-graphql and adding a .graphqlrc.json to my project root I get this error message. What could have gone wrong here?

**Comment by nstylo** [comment]
Oh, I use [vim-polyglot](https://github.com/sheerun/vim-polyglot) which comes with vim-graphql.

**Comment by felippepuhle** [comment]
This package has been deprecated, you can still have the same functionalities using the [LSP config on CoC](https://github.com/neoclide/coc.nvim/wiki/Language-servers\#graphql). 

Also, your problem may have been fixed on a new version of the language server (which this CoC extension doesn't provide). Feel free to reopen this issue if needed, or even contacting the [GraphQL LSP folks](https://github.com/graphql/graphiql) directly.

Thanks!

**Comment by jalalmanafi** [comment]
Same issue in VSCode , can anyone helps me ?
